package hr.ferit.dejanmihic.campspottercompose.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val LightBlue = Color(0xFF89CCF9)
val MediumBlue = Color(0xFF4EADEE)
val DarkerBlue = Color(0xFF1480CA)
val DarkBlue = Color(0xFF00558F)

val md_theme_light_primary = Color(0xFF075DB4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3D)
val md_theme_light_secondary = Color(0xFF006684)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF984062)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF302175)
val md_theme_light_inversePrimary = Color(0xFFA9C7FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF075DB4)
val md_theme_light_outlineVariant = Color(0xFFC4C6CF)
val md_theme_light_scrim = Color(0xFF000000)


val md_theme_dark_primary = Color(0xFFA9C7FF)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_primaryContainer = Color(0xFF00468B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFF6AD3FF)
val md_theme_dark_onSecondary = Color(0xFF003546)
val md_theme_dark_secondaryContainer = Color(0xFF004D65)
val md_theme_dark_onSecondaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_tertiary = Color(0xFFFFB0C9)
val md_theme_dark_onTertiary = Color(0xFF5E1133)
val md_theme_dark_tertiaryContainer = Color(0xFF7B294A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF1B0261)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1B0261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF075DB4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA9C7FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFFFFFFFF)


val seed = Color(0xFF68A4FF)